from hq.common import SimpleOrgNode, Replica
from orger.common import dt_heading

from hq.modules import kindle


class KindleView(Replica):
    """
        KindleView.main()
            - https://github.com/karlicoss/orger/blob/928f17947b27648deed7da6105da43cb4208e42d/src/orger/org_view.py#L104
    """
    DEFAULT_HEADER = '''
#+title: [Replica] Kindle Highlights
# This file is AUTOGENERATED by {tool}
# It's deliberately read-only, because it will be overwritten next time Orger is run.
# If you want to edit it anyway, you can use chmod +w in your terminal, or M-x toggle-read-only in Emacs.
'''.lstrip()

    def get_items(self):
        for title, highlights in kindle.get_highlights().items():
            yield title, SimpleOrgNode(
                heading='',
                children=[SimpleOrgNode('* ' + title)] + [SimpleOrgNode(i) for i in highlights]
            )


if __name__ == '__main__':
    KindleView.main()
